# Extract Data from UCI and Kaggle

This notebook extracts data from UCI Machine Learning Repository and Kaggle datasets and saves them in the project's Data folder.

## UCI Machine Learning Repository

In [59]:
import pandas as pd
from ucimlrepo import fetch_ucirepo

# fetch dataset
phiusiil_phishing_url_website = fetch_ucirepo(id=967)

# data (as pandas dataframes)
data = phiusiil_phishing_url_website.data.original

data.to_pickle('../Data/raw/phishing_url_uci.pkl')

### Explore Data

In [62]:
data.shape

(235795, 56)

In [60]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 235795 entries, 0 to 235794
Data columns (total 56 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   FILENAME                    235795 non-null  str
 1   URL                         235795 non-null  str
 2   URLLength                   235795 non-null  int64
 3   Domain                      235795 non-null  str
 4   DomainLength                235795 non-null  int64
 5   IsDomainIP                  235795 non-null  int64
 6   TLD                         235795 non-null  str
 7   URLSimilarityIndex          235795 non-null  float64
 8   CharContinuationRate        235795 non-null  float64
 9   TLDLegitimateProb           235795 non-null  float64
 10  URLCharProb                 235795 non-null  float64
 11  TLDLength                   235795 non-null  int64
 12  NoOfSubDomain               235795 non-null  int64
 13  HasObfuscation              235795 non-null  int64
 14  NoOfObfuscatedChar          235795 non-null  int64
 15  ObfuscationRatio            235795 non-null  float64
 16  NoOfLettersInURL            235795 non-null  int64
 17  LetterRatioInURL            235795 non-null  float64
 18  NoOfDegitsInURL             235795 non-null  int64
 19  DegitRatioInURL             235795 non-null  float64
 20  NoOfEqualsInURL             235795 non-null  int64
 21  NoOfQMarkInURL              235795 non-null  int64
 22  NoOfAmpersandInURL          235795 non-null  int64
 23  NoOfOtherSpecialCharsInURL  235795 non-null  int64
 24  SpacialCharRatioInURL       235795 non-null  float64
 25  IsHTTPS                     235795 non-null  int64
 26  LineOfCode                  235795 non-null  int64
 27  LargestLineLength           235795 non-null  int64
 28  HasTitle                    235795 non-null  int64
 29  Title                       235795 non-null  str
 30  DomainTitleMatchScore       235795 non-null  float64
 31  URLTitleMatchScore          235795 non-null  float64
 32  HasFavicon                  235795 non-null  int64
 33  Robots                      235795 non-null  int64
 34  IsResponsive                235795 non-null  int64
 35  NoOfURLRedirect             235795 non-null  int64
 36  NoOfSelfRedirect            235795 non-null  int64
 37  HasDescription              235795 non-null  int64
 38  NoOfPopup                   235795 non-null  int64
 39  NoOfiFrame                  235795 non-null  int64
 40  HasExternalFormSubmit       235795 non-null  int64
 41  HasSocialNet                235795 non-null  int64
 42  HasSubmitButton             235795 non-null  int64
 43  HasHiddenFields             235795 non-null  int64
 44  HasPasswordField            235795 non-null  int64
 45  Bank                        235795 non-null  int64
 46  Pay                         235795 non-null  int64
 47  Crypto                      235795 non-null  int64
 48  HasCopyrightInfo            235795 non-null  int64
 49  NoOfImage                   235795 non-null  int64
 50  NoOfCSS                     235795 non-null  int64
 51  NoOfJS                      235795 non-null  int64
 52  NoOfSelfRef                 235795 non-null  int64
 53  NoOfEmptyRef                235795 non-null  int64
 54  NoOfExternalRef             235795 non-null  int64
 55  label                       235795 non-null  int64
dtypes: float64(10), int64(41), str(5)
memory usage: 100.7 MB

In [61]:
data.head()

,FILENAME,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,...,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
0,521848.txt,https://www.southbankmosaics.com,31,www.southbankmosaics.com,24,0,com,100.0,1.000000,0.522907,...,0,0,1,34,20,28,119,0,124,1
1,31372.txt,https://www.uni-mainz.de,23,www.uni-mainz.de,16,0,de,100.0,0.666667,0.032650,...,0,0,1,50,9,8,39,0,217,1
2,597387.txt,https://www.voicefmradio.co.uk,29,www.voicefmradio.co.uk,22,0,uk,100.0,0.866667,0.028555,...,0,0,1,10,2,7,42,2,5,1
3,554095.txt,https://www.sfnmjournal.com,26,www.sfnmjournal.com,19,0,com,100.0,1.000000,0.522907,...,1,1,1,3,27,15,22,1,31,1
4,151578.txt,https://www.rewildingargentina.org,33,www.rewildingargentina.org,26,0,org,100.0,1.000000,0.079963,...,1,0,1,244,15,34,72,1,85,1

## Kaggle Datasets

In [70]:
import kagglehub
from pathlib import Path
import shutil

# Define data folder
data_folder = Path.cwd().parent / "Data" / "raw"

# List of datasets to download from Kaggle
list_of_files = [
    # url attrivutes data
    "simaanjali/tes-upload",
    "simaanjali/phising-detection-dataset",
    "nitsey/dataset-phising-website",
    "eswarchandt/phishing-website-detector",
     # phising site urls
    "taruntiwarihp/phishing-site-urls",
     # top searches
    "cheedcheed/top1m"
]

# clean up temp files from previous runs
shutil.rmtree(data_folder)

for dataset in list_of_files:
    # Download latest version
    path = kagglehub.dataset_download(dataset)
    # Move data to project data folder
    # kaggle_dataset_dir = Path(path)
    kaggle_dataset_dir = Path(path).parent.parent.parent.parent

    for item in kaggle_dataset_dir.iterdir():
        print(item)
        dest_path = data_folder / item.name
        print(dest_path)
        shutil.move(str(item), str(dest_path))

Downloading to C:\Users\kazos\.cache\kagglehub\datasets\simaanjali\tes-upload\1.archive...

100%|██████████| 4.74M/4.74M [00:01<00:00, 3.17MB/s]

Extracting files...

C:\Users\kazos\.cache\kagglehub\datasets\simaanjali
C:\dev\projects\ml-url\Data\raw\simaanjali
Downloading to C:\Users\kazos\.cache\kagglehub\datasets\simaanjali\phising-detection-dataset\1.archive...

100%|██████████| 4.36M/4.36M [00:01<00:00, 4.01MB/s]

Extracting files...

C:\Users\kazos\.cache\kagglehub\datasets\simaanjali
C:\dev\projects\ml-url\Data\raw\simaanjali
Downloading to C:\Users\kazos\.cache\kagglehub\datasets\nitsey\dataset-phising-website\2.archive...

100%|██████████| 1.88M/1.88M [00:00<00:00, 2.58MB/s]

Extracting files...

C:\Users\kazos\.cache\kagglehub\datasets\nitsey
C:\dev\projects\ml-url\Data\raw\nitsey
Downloading to C:\Users\kazos\.cache\kagglehub\datasets\eswarchandt\phishing-website-detector\3.archive...

100%|██████████| 197k/197k [00:00<00:00, 407kB/s]

Extracting files...

C:\Users\kazos\.cache\kagglehub\datasets\eswarchandt
C:\dev\projects\ml-url\Data\raw\eswarchandt
Downloading to C:\Users\kazos\.cache\kagglehub\datasets\taruntiwarihp\phishing-site-urls\1.archive...

100%|██████████| 9.03M/9.03M [00:01<00:00, 5.77MB/s]

Extracting files...

C:\Users\kazos\.cache\kagglehub\datasets\taruntiwarihp
C:\dev\projects\ml-url\Data\raw\taruntiwarihp
Downloading to C:\Users\kazos\.cache\kagglehub\datasets\cheedcheed\top1m\1.archive...

100%|██████████| 9.56M/9.56M [00:01<00:00, 5.22MB/s]

Extracting files...

C:\Users\kazos\.cache\kagglehub\datasets\cheedcheed
C:\dev\projects\ml-url\Data\raw\cheedcheed

## Explore Kaggle Data

### simaanjali/tes-upload

In [79]:
csv_1_file = data_folder / "simaanjali" / "tes-upload" / "versions" / "1" / "Phising_dataset_predict.csv"

dataset_1_phishing_df = pd.read_csv(csv_1_file).drop(columns=['Unnamed: 0'])

In [85]:
dataset_1_phishing_df.shape

(662591, 12)

In [84]:
dataset_1_phishing_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 662591 entries, 0 to 662590
Data columns (total 12 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   NumDots             662591 non-null  int64
 1   UrlLength           662591 non-null  int64
 2   AtSymbol            662591 non-null  int64
 3   NumDash             662591 non-null  int64
 4   NumPercent          662591 non-null  int64
 5   NumQueryComponents  662591 non-null  int64
 6   IpAddress           662591 non-null  int64
 7   HttpsInHostname     662591 non-null  int64
 8   PathLevel           662591 non-null  int64
 9   PathLength          662591 non-null  int64
 10  NumNumericChars     662591 non-null  int64
 11  Phising             630071 non-null  float64
dtypes: float64(1), int64(11)
memory usage: 60.7 MB

In [86]:
dataset_1_phishing_df.head()

,NumDots,UrlLength,AtSymbol,NumDash,NumPercent,NumQueryComponents,IpAddress,HttpsInHostname,PathLevel,PathLength,NumNumericChars,Phising
0,3,72,0,0,0,0,0,0,5,44,0,1.0
1,3,144,0,0,0,2,0,0,3,16,41,1.0
2,3,58,0,0,0,0,0,0,2,24,0,1.0
3,3,79,0,1,0,0,0,0,6,50,0,1.0
4,3,46,0,0,0,0,0,0,4,29,2,1.0

### simaanjali/phising-detection-dataset

In [87]:
csv_2_file = data_folder / "simaanjali" / "simaanjali" / "phising-detection-dataset" / "versions" / "1" / "Phising_Detection_Dataset.csv"

dataset_2_phishing_df = pd.read_csv(csv_2_file).drop(columns=['Unnamed: 0'])

In [88]:
dataset_2_phishing_df.shape

(662591, 10)

In [89]:
dataset_2_phishing_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 662591 entries, 0 to 662590
Data columns (total 10 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   NumDots          662591 non-null  int64
 1   UrlLength        662591 non-null  int64
 2   NumDash          662591 non-null  int64
 3   AtSymbol         662591 non-null  int64
 4   IpAddress        662591 non-null  int64
 5   HttpsInHostname  662591 non-null  int64
 6   PathLevel        662591 non-null  int64
 7   PathLength       662591 non-null  int64
 8   NumNumericChars  662591 non-null  int64
 9   Phising          630071 non-null  float64
dtypes: float64(1), int64(9)
memory usage: 50.6 MB

In [90]:
dataset_2_phishing_df.head()

,NumDots,UrlLength,NumDash,AtSymbol,IpAddress,HttpsInHostname,PathLevel,PathLength,NumNumericChars,Phising
0,3,72,0,0,0,0,5,44,0,1.0
1,3,144,0,0,0,0,3,16,41,1.0
2,3,58,0,0,0,0,2,24,0,1.0
3,3,79,1,0,0,0,6,50,0,1.0
4,3,46,0,0,0,0,4,29,2,1.0

### nitsey/dataset-phising-website

In [92]:
csv_3_file = data_folder / "nitsey" / "dataset-phising-website" / "versions" / "2" / "Dataset Phising Website.csv"

dataset_3_phishing_df = pd.read_csv(csv_3_file)

In [94]:
dataset_3_phishing_df.shape

(22110, 32)

In [95]:
dataset_3_phishing_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 22110 entries, 0 to 22109
Data columns (total 32 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   index                        22110 non-null  int64
 1   having_IP_Address            22110 non-null  int64
 2   URL_Length                   22110 non-null  int64
 3   Shortining_Service           22110 non-null  int64
 4   having_At_Symbol             22110 non-null  int64
 5   double_slash_redirecting     22110 non-null  int64
 6   Prefix_Suffix                22110 non-null  int64
 7   having_Sub_Domain            22110 non-null  int64
 8   SSLfinal_State               22110 non-null  int64
 9   Domain_registeration_length  22110 non-null  int64
 10  Favicon                      22110 non-null  int64
 11  port                         22110 non-null  int64
 12  HTTPS_token                  22110 non-null  int64
 13  Request_URL                  22110 non-null  int64
 14  URL_of_Anchor                22110 non-null  int64
 15  Links_in_tags                22110 non-null  int64
 16  SFH                          22110 non-null  int64
 17  Submitting_to_email          22110 non-null  int64
 18  Abnormal_URL                 22110 non-null  int64
 19  Redirect                     22110 non-null  int64
 20  on_mouseover                 22110 non-null  int64
 21  RightClick                   22110 non-null  int64
 22  popUpWidnow                  22110 non-null  int64
 23  Iframe                       22110 non-null  int64
 24  age_of_domain                22110 non-null  int64
 25  DNSRecord                    22110 non-null  int64
 26  web_traffic                  22110 non-null  int64
 27  Page_Rank                    22110 non-null  int64
 28  Google_Index                 22110 non-null  int64
 29  Links_pointing_to_page       22110 non-null  int64
 30  Statistical_report           22110 non-null  int64
 31  Result                       22110 non-null  int64
dtypes: int64(32)
memory usage: 5.4 MB

In [96]:
dataset_3_phishing_df.head()

,index,having_IP_Address,URL_Length,Shortining_Service,having_At_Symbol,double_slash_redirecting,Prefix_Suffix,having_Sub_Domain,SSLfinal_State,Domain_registeration_length,...,popUpWidnow,Iframe,age_of_domain,DNSRecord,web_traffic,Page_Rank,Google_Index,Links_pointing_to_page,Statistical_report,Result
0,0,-1,1,1,1,-1,-1,-1,-1,-1,...,1,1,-1,-1,-1,-1,1,1,-1,-1
1,1,1,1,1,1,1,-1,0,1,-1,...,1,1,-1,-1,0,-1,1,1,1,-1
2,2,1,0,1,1,1,-1,-1,-1,-1,...,1,1,1,-1,1,-1,1,0,-1,-1
3,3,1,0,1,1,1,-1,-1,-1,1,...,1,1,-1,-1,1,-1,1,-1,1,-1
4,4,1,0,-1,1,1,-1,1,1,-1,...,-1,1,-1,-1,0,-1,1,1,1,1

### eswarchandt/phishing-website-detector

In [98]:
csv_4_file = data_folder / "eswarchandt" / "phishing-website-detector" / "versions" / "3" / "phishing.csv"

dataset_4_phishing_df = pd.read_csv(csv_4_file)

In [99]:
dataset_4_phishing_df.shape

(11054, 32)

In [100]:
dataset_4_phishing_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11054 entries, 0 to 11053
Data columns (total 32 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Index                11054 non-null  int64
 1   UsingIP              11054 non-null  int64
 2   LongURL              11054 non-null  int64
 3   ShortURL             11054 non-null  int64
 4   Symbol@              11054 non-null  int64
 5   Redirecting//        11054 non-null  int64
 6   PrefixSuffix-        11054 non-null  int64
 7   SubDomains           11054 non-null  int64
 8   HTTPS                11054 non-null  int64
 9   DomainRegLen         11054 non-null  int64
 10  Favicon              11054 non-null  int64
 11  NonStdPort           11054 non-null  int64
 12  HTTPSDomainURL       11054 non-null  int64
 13  RequestURL           11054 non-null  int64
 14  AnchorURL            11054 non-null  int64
 15  LinksInScriptTags    11054 non-null  int64
 16  ServerFormHandler    11054 non-null  int64
 17  InfoEmail            11054 non-null  int64
 18  AbnormalURL          11054 non-null  int64
 19  WebsiteForwarding    11054 non-null  int64
 20  StatusBarCust        11054 non-null  int64
 21  DisableRightClick    11054 non-null  int64
 22  UsingPopupWindow     11054 non-null  int64
 23  IframeRedirection    11054 non-null  int64
 24  AgeofDomain          11054 non-null  int64
 25  DNSRecording         11054 non-null  int64
 26  WebsiteTraffic       11054 non-null  int64
 27  PageRank             11054 non-null  int64
 28  GoogleIndex          11054 non-null  int64
 29  LinksPointingToPage  11054 non-null  int64
 30  StatsReport          11054 non-null  int64
 31  class                11054 non-null  int64
dtypes: int64(32)
memory usage: 2.7 MB

In [101]:
dataset_4_phishing_df.head()

,Index,UsingIP,LongURL,ShortURL,Symbol@,Redirecting//,PrefixSuffix-,SubDomains,HTTPS,DomainRegLen,...,UsingPopupWindow,IframeRedirection,AgeofDomain,DNSRecording,WebsiteTraffic,PageRank,GoogleIndex,LinksPointingToPage,StatsReport,class
0,0,1,1,1,1,1,-1,0,1,-1,...,1,1,-1,-1,0,-1,1,1,1,-1
1,1,1,0,1,1,1,-1,-1,-1,-1,...,1,1,1,-1,1,-1,1,0,-1,-1
2,2,1,0,1,1,1,-1,-1,-1,1,...,1,1,-1,-1,1,-1,1,-1,1,-1
3,3,1,0,-1,1,1,-1,1,1,-1,...,-1,1,-1,-1,0,-1,1,1,1,1
4,4,-1,0,-1,1,-1,-1,1,1,-1,...,1,1,1,1,1,-1,1,-1,-1,1

### taruntiwarihp/phishing-site-urls

In [102]:
csv_5_file = data_folder / "taruntiwarihp" / "phishing-site-urls" / "versions" / "1" / "phishing_site_urls.csv"

dataset_5_phishing_df = pd.read_csv(csv_5_file)

In [103]:
dataset_5_phishing_df.shape

(549346, 2)

In [104]:
dataset_5_phishing_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 549346 entries, 0 to 549345
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   URL     549346 non-null  str
 1   Label   549346 non-null  str
dtypes: str(2)
memory usage: 8.4 MB

In [105]:
dataset_5_phishing_df.head()

                                                 URL Label
0  nobell.it/70ffb52d079109dca5664cce6f317373782/...   bad
1  www.dghjdgf.com/paypal.co.uk/cycgi-bin/webscrc...   bad
2  serviciosbys.com/paypal.cgi.bin.get-into.herf....   bad
3  mail.printakid.com/www.online.americanexpress....   bad
4  thewhiskeydregs.com/wp-content/themes/widescre...   bad

### cheedcheed/top1m

In [106]:
csv_6_file = data_folder / "cheedcheed" / "top1m" / "versions" / "1" / "top-1m.csv"

dataset_6_phishing_df = pd.read_csv(csv_6_file)

In [107]:
dataset_6_phishing_df.shape

(999999, 2)

In [108]:
dataset_6_phishing_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 999999 entries, 0 to 999998
Data columns (total 2 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   1           999999 non-null  int64
 1   google.com  999999 non-null  str
dtypes: int64(1), str(1)
memory usage: 15.3 MB

In [109]:
dataset_6_phishing_df.head()

   1     google.com
0  2    youtube.com
1  3   facebook.com
2  4      baidu.com
3  5  wikipedia.org
4  6      yahoo.com